# Cloud Build CD: update env-repo manifest (GitOps)
steps:
  - name: 'gcr.io/cloud-builders/git'
    id: Clone env-repo
    entrypoint: bash
    args:
      - -ceu
      - |
        git config --global user.email "ci-bot@$PROJECT_ID.iam.gserviceaccount.com"
        git config --global user.name "Cloud Build Bot"

        # 🔹 Skonfiguruj GitHub auth przez Secret Manager
        GITHUB_TOKEN=$(gcloud secrets versions access latest --secret=github-token)
        git config --global credential.helper store
        echo "https://$GITHUB_TOKEN@github.com" > ~/.git-credentials

        git clone https://github.com/twixy1905-stack/${_ENV_REPO}.git && cd ${_ENV_REPO}
        git checkout ${_ENV_BRANCH}

        sed -i "s|image: .*|image: ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_AR_REPO}/myapp:$SHORT_SHA|" k8s/deployment.yaml

        git add k8s/deployment.yaml
        git commit -am "Update image to $SHORT_SHA"
        git push origin ${_ENV_BRANCH}

substitutions:
  _REGION: us-central1
  _AR_REPO: my-repo
  _ENV_REPO: env-repo
  _ENV_BRANCH: main

options:
  logging: CLOUD_LOGGING_ONLY
