steps:
  - name: 'gcr.io/cloud-builders/gcloud'
    id: Auth GKE
    args:
      - 'container'
      - 'clusters'
      - 'get-credentials'
      - '${_CLUSTER}'
      - '--region'
      - '${_REGION}'
      - '--project'
      - '$PROJECT_ID'

  - name: 'gcr.io/cloud-builders/kubectl'
    id: Deploy
    entrypoint: bash
    args:
      - -c
      - |
        gcloud container clusters get-credentials ${_CLUSTER} --region ${_REGION} --project $PROJECT_ID
        kubectl apply -f k8s/deployment.yaml

substitutions:
  _CLUSTER: my-gke-cluster
  _REGION: us-central1

options:
  logging: CLOUD_LOGGING_ONLY
